global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'clickhouse'
    scrape_interval: 30s
    static_configs:
      - targets: ['clickhouse:9126']
  - job_name: 'log-analyzer'
    scrape_interval: 10s
    metrics_path: /
    static_configs:
      - targets: ['log-analyzer:9110']